name: Run go tests and upload coverage
description: Run go tests and upload coverage

inputs:
  branch:
    required: false
    default: "main"
    description: "Branch"
  go-version:
    required: true
    default: 1.23.4
    description: "Version of go"

env:
  GITHUB_TOKEN: "As provided by Github Actions"
  CODECOV_TOKEN: "Token for Codecov"

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.4

    - name: Install dependencies
      run: go mod tidy
      shell: bash

    - name: Run tests
      run: go test -covermode=set ./... -coverprofile=coverage.txt
      shell: bash

    - name: Debug info
      run: |
        echo "Repo: ${{ github.repository }}"
      shell: bash
    - name: Test if CODECOV_TOKEN is available
      run: |
        if [ -z "${{ env.CODECOV_TOKEN }}" ]; then
          echo "CODECOV_TOKEN is NOT set"
        else
          echo "CODECOV_TOKEN is available"
        fi
      shell: bash
    - name: Debug Codecov Upload
      run: bash <(curl -s https://codecov.io/bash) -t ${{ env.CODECOV_TOKEN }} -f coverage.txt -r github.com/${{ github.repository }}
      shell: bash
      env:
        GH_TOKEN: ${{ env.GITHUB_TOKEN }}
        CODECOV_TOKEN: ${{ env.CODECOV_TOKEN }}

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      env:
        GH_TOKEN: ${{ env.GITHUB_TOKEN }}
        CODECOV_TOKEN: ${{ env.CODECOV_TOKEN }}
      with:
        token: ${{ env.CODECOV_TOKEN }}
        files: coverage.txt
        name: ${{ github.workflow }}
        fail_ci_if_error: true
        verbose: true